{{ if ne .chezmoi.fqdnHostname "*.osc.edu" }}
[".antidote"]
    type = "archive"
    url = "https://github.com/mattmc3/antidote/archive/refs/tags/v1.9.0.tar.gz"
    stripComponents = 1
    # clone.args = ["--depth 1"]
# [".oh-my-zsh"]
#     type = "archive"
#     url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
#     type = "archive"
#     url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/themes/powerlevel10k"]
#     type = "archive"
#     url = "https://github.com/romkatv/powerlevel10k/archive/v1.18.0.tar.gz"
#     exact = true
#     stripComponents = 1
# [".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
#     type = "archive"
#     url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
# [".oh-my-zsh/custom/plugins/zsh-autocomplete"]
#     type = "archive"
#     url = "https://github.com/marlonrichert/zsh-autocomplete/archive/refs/tags/22.01.21.tar.gz"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
[".config/emacs"]
    type = "archive"
    url = "https://github.com/doomemacs/doomemacs/archive/master.tar.gz"
    stripComponents = 1
{{ end }}
