#!/usr/bin/env zsh
alias cz="chezmoi"
alias wpa="workpass"
alias em="emacsclient -nw"

# Taskwarrior related aliases
alias t="task"
alias in="task add +in"
alias tw="task -@home -@music"
alias th="task -@work"
alias tam="task add proj:Listening +Y2023 +@music"
alias tal="task add proj:Learning +@learning +c"

# kubectl
alias k="kubecolor"
alias kg="kubecolor get"
alias kd="kubecolor describe"

# beets
alias beet="beet -c $HOME/beets/config.yaml"
