format = """
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$kubernetes\
$python
$username\
$hostname\
$directory\
$character
"""
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_metrics]
disabled = false

[git_status]
ahead = ''
behind = ''
diverged = '󰡏'
deleted = ""
# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[󰁕](bold green)'
error_symbol = '[](bold red)'
vicmd_symbol = '[](bold purple)'
#success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[directory]
truncation_symbol = ".../"
truncate_to_repo = false
truncation_length = 8
repo_root_style = 'underline white'

[direnv]
disabled = false
style = "bright-yellow"

[package]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[python]
format = 'using [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ''
version_format = '${raw}' # shows the whole version, like 3.11.3

[gcloud]
detect_env_vars = ['GCLOUD_ACTIVE']

[aws]
disabled = true

[username]
format = '[$user]($style)@'
style_user = 'bold cyan'
style_root = 'bold red'

[hostname]
ssh_only = true
format = '[$hostname]($style) '
